# Generated by Django 3.2.8 on 2021-10-28 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Yosh')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Aktyor',
                'verbose_name_plural': 'Aktyorlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriya')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategpriyalar',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('descriptions', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Tagline')),
                ('discription', models.TextField(verbose_name='Description')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Poster')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Chiqqan yil')),
                ('country', models.CharField(max_length=30, verbose_name='Davlat')),
                ('worl_premiere', models.DateField(default=datetime.date(2021, 10, 28), verbose_name='Dunyoga korsatilgan vaqti')),
                ('budget', models.PositiveIntegerField(default=0, help_text='Summani dollarda korsating', verbose_name='Budjet')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='Summani dollarda korsating', verbose_name='AQSHda tolovlar')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='Summani dollarda korsating', verbose_name='Dunyoda tolovlar')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Chernovek')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='movies.Actor', verbose_name='aktorlar')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.category', verbose_name='Kategoriya')),
                ('directors', models.ManyToManyField(related_name='film_director', to='movies.Actor', verbose_name='rejissor')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='janrlar')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Yulduz reytingi',
                'verbose_name_plural': 'Yulduzlar reytingi',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('text', models.TextField(max_length=5000, verbose_name='Xabar')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Kino')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.reviews', verbose_name='Otasi')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP adress')),
                ('movie', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='movies.movies', verbose_name='Kino')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ratingstar', verbose_name='Yulduzcha')),
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reytinglar',
            },
        ),
        migrations.CreateModel(
            name='Movie_shots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('discription', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Rasm')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Kino')),
            ],
            options={
                'verbose_name': 'Kinodan kadr',
                'verbose_name_plural': 'Kinodan kadrlar',
            },
        ),
    ]
