# Generated by Django 3.2.8 on 2021-10-28 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='worl_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Dunyoga korsatilgan vaqti'),
        ),
    ]
