# Generated by Django 3.2.8 on 2021-10-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_movie_shots_movieshots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='discription',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='movieshots',
            old_name='discription',
            new_name='descriptions',
        ),
    ]
