# Generated by Django 3.2.9 on 2021-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211103_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='genre',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='movies',
            name='country_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Davlat'),
        ),
        migrations.AddField(
            model_name='movies',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='movies',
            name='tagline_uz',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='movies',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
